### ISSUE TITLE
All your images are stretched/smashed

### ISSUE THREAD

**Issue by Explosion-Scratch** [wgyt/wgyt-tk-v5#17]
Use this CSS on them to preserve the intended aspect ratio by cropping them to the correct size:
```css
img {
  object-fit: cover;
}
```
