### ISSUE TITLE
make scroll bar nice

### ISSUE THREAD

**Issue by wgyt** [wgyt/wgyt-tk-v5#50]
like youtube's scroll bar

**Comment by wgyt** [comment]
```css
/* Works on Firefox */
* {
  scrollbar-width: thin;
  scrollbar-color: gray #00000000;
}

/* Works on Chrome, Edge, and Safari */
*::-webkit-scrollbar {
  width: 12px;
}

*::-webkit-scrollbar-track {
  background:  #00000000;
}

*::-webkit-scrollbar-thumb {
  background-color: gray;
  border-radius: 20px;
  border: 3px solid #00000000;
}
```
need to add this css to the site for it to work
